### ISSUE TITLE
When setting the configuration "dense_desc": I get the following error

### ISSUE THREAD

**Issue by ahong007007** [lzx551402/contextdesc#12]
When setting the configuration "python image_matching.py  --dense_desc", I get the following error

'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'input/img:0' refers to a Tensor which does not exist. The operation, 'input/img', does not exist in the graph.

**Comment by lzx551402** [comment]
The correct command you should call is "python3 image_matching.py --dense_desc --loc_model pretrained/dense-contextdesc". By default you are using contextdesc++ in this script.

**Comment by lzx551402** [comment]
I assume that this issue has been resolved, and close this thread.
