### ISSUE TITLE
A problem about protobuf file

### ISSUE THREAD

**Issue by Archaon6734** [lzx551402/contextdesc#13]
Your work is great!But I can't find the link to download protobuf file,Did I miss something?
Thanks!

**Comment by lzx551402** [comment]
On the README page, a table has listed all valid models and their download links. For example, for ContextDesc++, https://research.altizure.com/data/contextdesc_models/contextdesc_pp.tar.

**Comment by lzx551402** [comment]
I assume that this issue has been resolved, and close this thread.
