### ISSUE TITLE
Some question about the Geometric context encoder

### ISSUE THREAD

**Issue by cvlearn913** [lzx551402/contextdesc#14]
1. Is the network input the coordinates of keypoint? 
2. How do I get keypoint? Is it using sift?
 3. Is keypoint extracted from the original image or on the sampled patch? 
4.What does the perceptron mean? Because I only found the definition of visual context in augdesc.py
Thanks for your help!

**Comment by lzx551402** [comment]
1. as the paper describes, the inputs are both the keypoint locations and visual descriptors (to encode a keypoint matchability).
2. in the example script provided, it uses SIFT.
3. of course from original image. refer to the code.
4. means MLP. it is also used in the geometric context encoder.

**Comment by lzx551402** [comment]
I assume that this issue has been resolved, and close this thread.
