### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by knsong** [lzx551402/contextdesc#2]
hi 
thanks for the work first,
can you share me a copy of the training data?
Thank you!

**Comment by lzx551402** [comment]
Hi,

As described on the project page, part of the training data has been released in [GL3D](https://github.com/lzx551402/GL3D), and we plan to provide more helper functions after CVPR to help you prepare the training sets for, e.g., TensorFlow. Stay tuned.

**Comment by engraamirkhan** [comment]
Hi,

That would be a great assistance.
Thank you and Congrats.
