### ISSUE TITLE
Invalid link.

### ISSUE THREAD

**Issue by vMagina** [lzx551402/contextdesc#20]
Can you update the link about your CVPR intermediate results of keypoint locations and image patches for HPSequences?

**Comment by cvlearn913** [comment]
Same situation the link was invalid

**Comment by lzx551402** [comment]
the link is now fixed. sorry for this trouble!

**Comment by vMagina** [comment]
> the link is now fixed. sorry for this trouble!

Thanks a lot.
I have used the hseq util you provide to generate patches .
