### ISSUE TITLE
How to perturb the patch?

### ISSUE THREAD

**Issue by vMagina** [lzx551402/contextdesc#22]
I use the original patches and keypoint coords as input and get the result, 64.13/71.84 for i/v sequences. There is some gap with result in the paper. When I do transformations directly on these patches, I get worst result. Thus, I guess that my transformations on the patches maybe wrong.
As described in the paper, you randomly perturb input patches by affine transformations including rotation (90°), anisotropic scaling and translation w.r.t. the detection scale.

1. So, are you transform the patch in this way : first, cropping patches from the undistorted image with the keypoint params; second, doing some transformation on them? Or, doing transformations on the undistorted image and then cropping the patches? Can you provide some examples?
2. The coords used in the context encoder are raw coords or perturbed coords?

I hope to receive your reply. Thanks a lot.

**Comment by lzx551402** [comment]
1. To perturb the patches, you simply perturb the transformation matrix that is used for patch cropping.

2. The coordinates used by geometric context is perturbed by random homography, while the coordinates used by visual context are not perturbed.

**Comment by lzx551402** [comment]
You may now refer to [this](https://github.com/lzx551402/tfmatch/blob/master/utils/npy_utils.py#L99) on how to generate a random affine matrix to perturb the input patch.

**Comment by vMagina** [comment]
> You may now refer to [this](https://github.com/lzx551402/tfmatch/blob/master/utils/npy_utils.py#L99) on how to generate a random affine matrix to perturb the input patch.

Thanks a lot. 
I have encounted a new problem. How do you do batch inference? Because the num of kpts is different among images.

**Comment by vMagina** [comment]
> > You may now refer to [this](https://github.com/lzx551402/tfmatch/blob/master/utils/npy_utils.py#L99) on how to generate a random affine matrix to perturb the input patch.
> 
> Thanks a lot. 
> I have encounted a new problem. How do you do batch inference? Because the num of kpts is different among images.

I have solved it.
