### ISSUE TITLE
Reconstruction methods

### ISSUE THREAD

**Issue by anorlo** [lzx551402/contextdesc#27]
Hello, I appreciate your sharing very much!
I wonder how you reconstruct buildings by this contextdesc as Figure.8 showed in your paper. Is there any pipeline of reconstruction or if you have any advice for applying a reconstruction? I look forward to any suggestions from you. Thank you!

**Comment by zjhthu** [comment]
you can use COLMAP, the [repo](https://github.com/ahojnnes/local-feature-evaluation) should help
