### ISSUE TITLE
Some questions about the visual context encoder

### ISSUE THREAD

**Issue by DreamBlack** [lzx551402/contextdesc#3]
I have some questions about the integration of regional feature and keypoints coordinates.

 Are the coordinates of keypoints defined in original image(H*W)? If so, for a keypoint, how to find its 3 nearest neighbors in regional feature(H/32*W/32) for interpolation? Transfer coordinates in original image to a image of size H/32*W/32 first?

Thank you very much!

**Comment by lzx551402** [comment]
Thank you for your interest in our work.

1. keypoint coordinates: As in Sec.4.1,  the input keypoint coordinates are normalized to [−1, 1] regarding the image size.
2. we just return from CVPR and will recently release the code for network construction to help to implement the work. Basically, you will use for example, tf.meshgrid, to generate the grid points associated with the regional features (also in [-1, 1]), then you will be able to use standard interpolation methods (similar to PointNet++) to convert the dimensions.

**Comment by knsong** [comment]
@lzx551402  why is the down sampling rate w.r.t input size H, W fixed `1/32`?  Shouldn't it be a dynamic number `1/resnet50_output_height(width)` since different images has different input size H, W?

**Comment by lzx551402** [comment]
@knsong I didn't get your point. For example you feed an image of 256x256, then its intermediate feature map from resnet50 would be sized 8x8. Similarly if it is 512x512, then you will get 16x16. The down-sample ratio is fixed due to strided convolutions, you can definitely feed images of different size.

**Comment by knsong** [comment]
@lzx551402 For example, if I feed an image of 500x500, I will get 16x16, and the down-sample ratio is not exactly 32.

**Comment by lzx551402** [comment]
@knsong Yes precisely you may always use the formula (W−F+2P)/S+1 to compute the exact output size. I used "1/32" in the paper just wanted to be comprehensive to present the main idea. In principle the network can take images of arbitrary size and does not require any resizing, unless they are too small (e.g., 32x32 does not fit ResNet) or too large that exceed the GPU memory.

**Comment by knsong** [comment]
@lzx551402 thanks!

**Comment by DreamBlack** [comment]
> Thank you for your interest in our work.
> 
> 1. keypoint coordinates: As in Sec.4.1,  the input keypoint coordinates are normalized to [−1, 1] regarding the image size.
> 2. we just return from CVPR and will recently release the code for network construction to help to implement the work. Basically, you will use for example, tf.meshgrid, to generate the grid points associated with the regional features (also in [-1, 1]), then you will be able to use standard interpolation methods (similar to PointNet++) to convert the dimensions.

Thank you!

**Comment by knsong** [comment]
@lzx551402 Can you share the tensorflow definition of the visual context encoder?

**Comment by lzx551402** [comment]
@DreamBlack @knsong 
The network definition is now available here. An usage is provided along with the image matching example. See README for details.
