### ISSUE TITLE
visual context encoder tensorflow definition

### ISSUE THREAD

**Issue by knsong** [lzx551402/contextdesc#6]
@lzx551402 Can you share the tensorflow definition of the visual context encoder, especially the inverse distance weighted interpolation module? Thanks!

**Comment by lzx551402** [comment]
@knsong 
The network definition is now available [here](https://github.com/lzx551402/contextdesc/tree/master/models/cnn_wrapper). An usage is provided along with the image matching example. See README for details.

**Comment by knsong** [comment]
@lzx551402 Thank you! I've implemented the context encoder by myself, but these will still greatly help!
